### ISSUE TITLE
Provide "validate" method

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/modspec-ruby#4]
We need to validate ModSpec instances

**Comment by ronaldtse** [comment]
@opoudjis could you help describe the cases you need for validation?

* Validation of single instance
* Validation of class
* Validation of a loaded set of classes/instances

Ones I can think of:
1. URI identifiers of ModSpec instances exist in the loaded collection 
2. No loops or identify reference loops (ie these requirements need to be satisfied together)
3. Presence of description and identifier
4. No duplicated identifiers
5. No missing doubly linked references (to and from)
6. The content of the description is valid (if in a particular rich text format)
7. No orphaned instance (every instance needs to belong to a class)

**Comment by opoudjis** [comment]
What I need, Ronald, is content in the spec so I know what the hell this gem does, because I don't, and I'm not going to waste your clients' time trying to work it out. I don't care what validation functionality you want to add to this gem, there is no validation in spec of what it already does.

If you're going to start developing code for this project, then you are going to be held to a far greater standard than this:

````
Dir.glob("spec/fixtures/*-rc.yaml").each do |file|
    it "parses normative statements class #{file}" do
      yaml = IO.read(file)
      ms = Modspec::Suite.from_yaml(yaml)

      # TODO: tests

    end
  end

  Dir.glob("spec/fixtures/*-cc.yaml").each do |file|
    it "parses conformance class #{file}" do
      yaml = IO.read(file)
      ms = Modspec::Suite.from_yaml(yaml)

      # TODO: tests

    end
  end
````

**Comment by opoudjis** [comment]
And if you seriously want to reimplement mn-requirements/modspec from scratch, including all its validation, without talking to me, spec files of mn-requirements are publicly available.

Right now, this is a naive attempt to reimplement mn-requirements/modspec/metanorma, with no idea about validation, no idea about Presentation XML, no idea about the cyclical dependencies and the conflict between anchors and identifiers. Just a bare shell of Shale on top of an object model. It's unusable, it does only the easy bit of mn-requirements/modspec, it is not thought through, and I will ignore it.

**Comment by ronaldtse** [comment]
It will never have anything to do with Presentation XML. 

You mentioned about the “easy bits”, so what are the difficult bits?

**Comment by opoudjis** [comment]
You need to say what exactly this code is meant to input and output, with test code, and why, and what bits of the existing mn-requirement code it is meant to replace. I don't know what you want this code to do, and I don't trust you.

Modspec Validation functionality is in 

https://github.com/metanorma/mn-requirements/blob/main/lib/metanorma/modspec/validate.rb
